# Generated by Django 4.0 on 2022-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_dislikes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
