# Generated by Django 4.1.3 on 2022-12-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_tags"),
    ]

    operations = [
        migrations.RenameModel(old_name="Tags", new_name="Tag",),
    ]
